// svelte/NodeComponent.svelte
<script>

    export let data;
    export let toolkit;
    export let surface;
    export let vertex;

    function removeNode() {
        toolkit.removeNode(vertex)
    }

</script>

<div data-jtk-target="true">
    {vertex.data.name}
    <div class="delete" title="Click to delete" on:click={() => removeNode()}/>
    <div class="connect" data-jtk-source="true"/>
</div>

// angular/src/app/node.component.ts
import {Component} from "@angular/core"
import {BaseNodeComponent} from "@jsplumbtoolkit/browser-ui-angular"


@Component({
  template:`<div data-jtk-target="true">
    {{obj['name']}}
    <div class="delete" title="Click to delete" (click)="this.removeNode()"></div>
    <div class="connect" data-jtk-source="true"></div>
  </div>`
})
export class NodeComponent extends BaseNodeComponent {

}
